decision_supi1:
  supi_imsi: "001010000059449"
  pcc_rules: 
    - non-gbr-rule-5qi-9
    - gbr-rule-5qi-1

decision_supi2:
  supi_imsi: "001010000059450"
  pcc_rules:
    - non-gbr-rule-5qi-9
    - gbr-rule-5qi-5

decision_supi3:
  supi_imsi: "001010000059445"
  pcc_rules:
    - gbr-rule-5qi-1

decision_dnn:
  dnn: default
  pcc_rules:
    - non-gbr-rule-5qi-9
    - gbr-rule-5qi-1

decision_default:
  default: true
  pcc_rules:
    - non-gbr-rule-5qi-9
    - gbr-rule-5qi-1

decision_slice:
  slice: 
    sst: 1
    sd: 000001
  pcc_rules:
    - non-gbr-rule-5qi-9
    - gbr-rule-5qi-1
