{{- if not .Values.config.mountConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
data:
  {{- range $key, $val := .Values.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- else }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
data:
  flexric.conf: |
      [NEAR-RIC]
      NEAR_RIC_IP = 192.168.100.244

      [XAPP]
      DB_PATH = /flexric/db/
      DB_NAME = xapp_rnis_db

  config.ini: |
      [XAPP]
      RemoteRabbitmqAddress = 192.168.100.245
      RemoteRabbitmqPort = 5672
      RemoteRabbitMqUsername = user
      RemoteRabbitMqPassword = password
      SQliteDBPath = /flexric/db/
      SQliteDBName = xapp_rnis_db
      LogLevel = info
      publishTime = 0.01  
{{- end }}