non-gbr-qos-5qi-9:
 5qi: 9
 arp:
   priorityLevel: 15
   preemptCap: NOT_PREEMPT
   preemptVuln: PREEMPTABLE
 priorityLevel: 10

gbr-qos-5qi-1:
 5qi: 1
 maxbrUl: 40 Mbps
 maxbrDl: 120 Mbps
 gbrUl: 30 Mbps
 gbrDl: 100 Mbps
 arp:
   priorityLevel: 1
   preemptCap: MAY_PREEMPT
   preemptVuln: NOT_PREEMPTABLE
 priorityLevel: 9

gbr-qos-5qi-5:
  5qi: 4
  maxbrUl: 10 Mbps
  maxbrDl: 110 Mbps
  gbrUl: 5 Mbps
  gbrDl: 50 Mbps
  arp:
    priorityLevel: 1
    preemptCap: MAY_PREEMPT
    preemptVuln: NOT_PREEMPTABLE
  priorityLevel: 8
