apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "oai-flexric.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: x
      port: 36421
      targetPort: 36421
      protocol: SCTP
  selector:
    {{- include "oai-flexric.selectorLabels" . | nindent 4 }}
