apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "oai-amf.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  #clusterIP: None
  ports:
    - name: http
      port: {{ .Values.exposedPorts.sbi }}
      targetPort: {{ .Values.exposedPorts.sbi }}
      protocol: TCP
  selector:
    {{- include "oai-amf.selectorLabels" . | nindent 4 }}