---
{{- if .Values.multus.f1Interface.create }}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: {{ .Chart.Name }}-f1
spec:
  config: '{ 
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": {{- cat .Values.multus.f1Interface.hostInterface | nospace | quote }},
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": {{- cat .Values.multus.f1Interface.ipAdd "/" .Values.multus.f1Interface.netmask | nospace | quote }}
                        {{- if .Values.multus.f1Interface.gateway }}
                        ,"gateway": {{- cat .Values.multus.f1Interface.gateway | nospace | quote }}
                        {{- end }}
                }
        ]
        {{- if .Values.multus.f1Interface.routes }}
        ,"routes":  {{- .Values.multus.f1Interface.routes | toJson }}
        {{- end }}
      }
    }'
{{- end }}
---
{{- if .Values.multus.ru1Interface.create }}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: {{ .Chart.Name }}-ru1
spec:
  config: '{ 
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": {{- cat .Values.multus.ru1Interface.hostInterface | nospace | quote }},
      {{- if .Values.multus.ru1Interface.mtu }}
      "mtu": {{ .Values.multus.ru1Interface.mtu }},
      {{- end }}
      "mode": "bridge",
      "ipam": {
        {{- if eq .Values.multus.ru1Interface.ipAdd "dhcp" }}
        "type": "dhcp",
        {{- else }}
        "type": "static",
        "addresses": [
                {
                        "address": {{- cat .Values.multus.ru1Interface.ipAdd "/" .Values.multus.ru1Interface.netmask | nospace | quote }}
                        {{- if .Values.multus.ru1Interface.gateway }}
                        ,"gateway": {{- cat .Values.multus.ru1Interface.gateway | nospace | quote }}
                        {{- end }}
                }
        ]
        {{- end }}
      }
    }'
{{- end }}
---
{{- if .Values.multus.ru2Interface.create }}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: {{ .Chart.Name }}-ru2
spec:
  config: '{ 
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": {{- cat .Values.multus.ru2Interface.hostInterface | nospace | quote }},
      {{- if .Values.multus.ru2Interface.mtu }}
      "mtu": {{ .Values.multus.ru2Interface.mtu }},
      {{- end }}
      "mode": "bridge",
      "ipam": {
        {{- if eq .Values.multus.ru2Interface.ipAdd "dhcp" }}
        "type": "dhcp",
        {{- else }}
        "type": "static",
        "addresses": [
                {
                        "address": {{- cat .Values.multus.ru2Interface.ipAdd "/" .Values.multus.ru2Interface.netmask | nospace | quote }}
                        {{- if .Values.multus.ru2Interface.gateway }}
                        ,"gateway": {{- cat .Values.multus.ru2Interface.gateway | nospace | quote }}
                        {{- end }}
                }
        ]
        {{- end }}
      }
    }'
{{- end }}

