{{- if .Values.includeTcpDumpContainer }}
{{- if .Values.persistent.sharedvolume }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cn5g-pvc
spec:
  accessModes:
    - ReadWriteMany
{{- if .Values.persistent.storageClass }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistent.storageClass }}"
{{- end }}
  resources:
    requests:
      storage: {{ .Values.persistent.size }}
{{- end }}
{{- end }}