non-gbr-rule-5qi-9:
  flowInfos:
    - flowDescription: permit out ip from any to assigned
  precedence: 10
  refQosData:
    - non-gbr-qos-5qi-9

gbr-rule-5qi-1:
  flowInfos:
    - flowDescription: permit out ip from 1.1.1.1 to assigned
  precedence: 9
  refQosData:
    - gbr-qos-5qi-1

gbr-rule-5qi-5:
  flowInfos:
    - flowDescription: permit out ip from 1.1.1.2 to assigned
  precedence: 8
  refQosData:
    - gbr-qos-5qi-5
