decision_supi1:
  supi_imsi: "208950000000032"
  pcc_rules: 
    - steering-rule-primary

decision_supi2:
  supi_imsi: "208950000000033"
  pcc_rules: 
    - steering-rule-secondary

decision_dnn:
  dnn: default
  pcc_rules:
    - steering-rule-primary
    - steering-rule-secondary

decision_slice:
  slice: 
    sst: 222
    sd: "123"
  pcc_rules:
    - steering-rule-primary
    - steering-rule-secondary
