apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "oai-gnb.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "oai-gnb.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "oai-gnb.selectorLabels" . | nindent 8 }}
        app: oai-gnb
    {{- if .Values.multus.n2Interface.create }}
      annotations:
        k8s.v1.cni.cncf.io/networks: >-
          [{
                 "name": "{{ .Chart.Name }}-n2",
                 "interface": "n2"
                {{- if .Values.multus.n2Interface.Mac }}
                 ,"mac":  "{{ .Values.multus.n2Interface.Mac }}"
                {{- end }}
                {{- if .Values.multus.defaultGateway }}
                 ,"default-route": ["{{ .Values.multus.defaultGateway }}"]
                {{- end }}
                {{- if .Values.multus.n2Interface.Gateway }}
                 ,"gateway": ["{{ .Values.multus.n2Interface.Gateway }}"]
                {{- end }}
          }
          {{- if .Values.multus.n3Interface.create }}
          ,{
                 "name": "{{ .Chart.Name }}-n3",
                 "interface": "n3"
                {{- if .Values.multus.n3Interface.Mac }}
                 ,"mac":  "{{ .Values.multus.n3Interface.Mac }}"
                {{- end }}
                {{- if .Values.multus.n3Interface.Gateway }}
                 ,"gateway": ["{{ .Values.multus.n3Interface.Gateway }}"]
                {{- end }}
          }
          {{- end }}
          {{- if .Values.multus.ru1Interface.create }}
          ,{
                 "name": "{{ .Chart.Name }}-ru1",
                 "interface": "ru1"
                {{- if .Values.multus.ru1Interface.Mac }}
                 ,"mac":  "{{ .Values.multus.ru1Interface.Mac }}"
                {{- end }}
                {{- if .Values.multus.ru1Interface.Gateway }}
                 ,"gateway": ["{{ .Values.multus.ru1Interface.Gateway }}"]
                {{- end }}
          }
          {{- end }}
          {{- if .Values.multus.ru2Interface.create }}
          ,{
                 "name": "{{ .Chart.Name }}-ru2",
                 "interface": "ru2"
                {{- if .Values.multus.ru2Interface.Mac }}
                 ,"mac":  "{{ .Values.multus.ru2Interface.Mac }}"
                {{- end }}
                {{- if .Values.multus.ru2Interface.Gateway }}
                 ,"gateway": ["{{ .Values.multus.ru2Interface.Gateway }}"]
                {{- end }}
          }
          {{- end }}
          ]
    {{- end }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.imagePullSecrets | indent 8 }}
    {{- end }}
      containers:
      - name: gnb
        image: "{{ .Values.nfimage.repository }}:{{ .Values.nfimage.version }}"
        imagePullPolicy: {{ .Values.nfimage.pullPolicy }}
        volumeMounts:
        {{- if eq .Values.config.usrp "aw2s" }}
          - mountPath: /opt/oai-gnb-aw2s/etc/gnb.conf
        {{- else }}
          - mountPath: /opt/oai-gnb/etc/gnb.conf
        {{- end }}
            name: configuration
            subPath: gnb.conf
          # USRP B210/B200 Mini
        {{- if eq .Values.config.usrp "b2xx"}}
          - mountPath: /dev/bus/usb/
            name: usrp
        {{- end}}
        {{- if .Values.resources.define}}
        resources:
          requests:
            memory: {{ .Values.resources.requests.nf.memory | quote }}
            cpu: {{ .Values.resources.requests.nf.cpu | quote }}
          limits:
            memory: {{ .Values.resources.limits.nf.memory | quote }}
            cpu: {{ .Values.resources.limits.nf.cpu | quote }}
        {{- end}}
        securityContext:
           privileged: true
           # capabilities:
           #    add:
           #     - NET_ADMIN
           #    drop:
           #     - ALL
        ports:
        - containerPort: 2152
          name: n3
          protocol: UDP
        - containerPort: 36412
          name: n2
          protocol: SCTP
        {{- if .Values.start.gnb}}
        command: [ "/bin/bash", "-c" ]
        args:
            sed -e s/@AMF_IP_ADDRESS@/$AMF_IP_ADDRESS/g
            {{- if eq .Values.config.usrp "b2xx"}}
                -e s/@GNB_IP_ADDRESS@/$GNB_IP_ADDRESS/g
            {{- end }}
            {{- if eq .Values.config.usrp "aw2s" }}
                /opt/oai-gnb-aw2s/etc/gnb.conf | tee /tmp/gnb.conf;
            {{- else }}
                /opt/oai-gnb/etc/gnb.conf | tee /tmp/gnb.conf;
            {{- end }}
          {{- if eq .Values.config.usrp "b2xx" }}
            /opt/oai-gnb/bin/uhd_images_downloader.py -t b2xx;
          {{- else if eq .Values.config.usrp "n3xx" }}
            /opt/oai-gnb/bin/uhd_images_downloader.py -t n3xx;
          {{- else if eq .Values.config.usrp "x3xx" }}
            /opt/oai-gnb/bin/uhd_images_downloader.py -t x3xx;
          {{- end }}
          {{- if eq .Values.config.usrp "aw2s" }}
            exec /opt/oai-gnb/bin/nr-softmodem -O /tmp/gnb.conf $USE_ADDITIONAL_OPTIONS;
          {{- else }}
            exec /opt/oai-gnb-aw2s/bin/nr-softmodem -O /tmp/gnb.conf $USE_ADDITIONAL_OPTIONS;
          {{- end }}
        {{- else}}
        command:
          - /bin/sleep
          - infinity
        {{- end}}
        env:
          - name: TZ
            value: {{ .Values.config.timeZone }}
          - name: USE_ADDITIONAL_OPTIONS
            value: {{ .Values.config.useAdditionalOptions }}
          - name: AMF_IP_ADDRESS
            value: {{ .Values.config.amfIpAddress }}
        {{- if eq .Values.config.usrp "b2xx" }}
          - name: GNB_IP_ADDRESS
            valueFrom: 
              fieldRef:
                fieldPath: status.podIP
        {{- end}}
      {{- if .Values.includeTcpDumpContainer }}
      - name: tcpdump
        image: "{{ .Values.tcpdumpimage.repository }}:{{ .Values.tcpdumpimage.version }}"
        imagePullPolicy: {{ .Values.tcpdumpimage.pullPolicy }}
        {{- if .Values.resources.define}}
        resources:
          requests:
            memory: {{ .Values.resources.requests.tcpdump.memory | quote }}
            cpu: {{ .Values.resources.requests.tcpdump.cpu | quote }}
          limits:
            memory: {{ .Values.resources.limits.tcpdump.memory | quote }}
            cpu: {{ .Values.resources.limits.tcpdump.cpu | quote }}
        {{- end}}
        securityContext:
           privileged: true
           capabilities:
              add:
               - NET_ADMIN
              drop:
               - ALL
        {{- if .Values.start.tcpdump}}
        command:
          - /bin/sh
          - -c
        {{- if eq .Values.config.usrp "b2xx" }}
          - /usr/sbin/tcpdump -ni any -w /pcap/oai-gnb-n2_`date +%Y-%m-%d_%H_%M-%S-%Z`.pcap
        {{- else}}
          - /usr/sbin/tcpdump -ni n2 src {{ .Values.config.amfIpAddress }} or dst {{ .Values.config.amfIpAddress }} -w /pcap/oai-gnb-n2_`date +%Y-%m-%d_%H_%M-%S-%Z`.pcap
        {{- end}}
          - /usr/sbin/tcpdump -i any -w /tmp/pcap/{{ .Chart.Name }}_`date +%Y-%m-%d_%H_%M-%S-%Z`.pcap
        {{- else}}
        command:
          - /bin/sleep
          - infinity
        {{- end}}
        {{- if .Values.persistent.sharedvolume }}
        volumeMounts:
        - mountPath: "/pcap"
          name: oai5g-pv
        {{- end}}
      {{- end }}
      volumes:
      {{- if .Values.persistent.sharedvolume }}
      - name: oai5g-pv
        persistentVolumeClaim:
          claimName: oai5g-pvc
      {{- end }}
      - configMap:
          name: {{ .Chart.Name }}-configmap
        name: configuration
      {{- if eq .Values.config.usrp "b2xx"}}
      - name: usrp
        hostPath:
          path: /dev/bus/usb/
      {{- end}}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: {{ .Values.serviceAccount.name }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- if .Values.nodeSelector}}
      nodeSelector: 
         {{- toYaml .Values.nodeSelector | nindent 12 }}
      {{- end }}
      {{- if .Values.nodeName}}
      nodeName: {{ .Values.nodeName }}
      {{- end }}
