apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: oai-kustomization
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/ocp-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: git-repository
    namespace: flux-system
  targetNamespace: oai-basic1

